name: Rename game file
on:
  workflow_dispatch:
jobs:
  rename:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Rename juego-de-lectura.html to index.html
        run: |
          git mv juego-lectura/juego-de-lectura.html juego-lectura/index.html
          git config user.name "TripleServices"
          git config user.email "TripleServices@users.noreply.github.com"
          git commit -m "Rename juego-de-lectura.html to juego-lectura/index.html"
          git push
